version: '3.7'
services:
  neo:
    image: neo4j:latest
    container_name: neo4j-database
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data/
    environment:
      - NEO4J_AUTH=none
      
volumes:
  neo4j_data:
networks:
  local:
    driver: bridge
