#  https://github.com/marcellodesales/neo4j-with-cypher-seed-docker
version: '3.0'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-database
    build:
      context: .
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./runtime/data:/data
      - ./runtime/logs:/logs
      - ./runtime/import:/var/lib/neo4j/import
      - ./runtime/plugins:/plugins
      - ./cypher_query.cql:/cyphers/interviews.cql
    environment:
      - NEO4J_AUTH=none
